version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 573664571276.dkr.ecr.us-west-2.amazonaws.com
      - REPOSITORY_URI=573664571276.dkr.ecr.us-west-2.amazonaws.com/topthree
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      # Run tests with built Docker images
      # - echo Run react tests...
      # - docker run -e CI=true lukondefmwila/react-test
      # - echo Run nodejs tests...
      # - docker run -e CI=true lukondefmwila/nodejs-test
      # Scan Docker image with Snyk
      ## Client
      ## Run test for security vulernabilities
      # - ./snyk test --severity-threshold=medium --docker lukondefmwila/react-test:latest --file=./client/Dockerfile.dev
      ## Setup continuous monitoring
      # - ./snyk monitor --docker lukondefmwila/react-test:latest --file=./client/Dockerfile.dev
      ## Backend
      ## Run test for security vulernabilities
      # - ./snyk test --severity-threshold=medium --docker lukondefmwila/nodejs-test:latest --file=./backend/Dockerfile.dev
      ## Setup continuous monitoring
      # - ./snyk monitor --docker lukondefmwila/nodejs-test:latest --file=./backend/Dockerfile.dev
      # Build the Docker images
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

      - docker build -t lukondefmwila/dkr-multicontainer-app-client ./client
      - docker tag lukondefmwila/dkr-multicontainer-app-client $REPOSITORY_URI:$IMAGE_TAG:client
      - docker build -t lukondefmwila/dkr-multicontainer-app-backend ./backend
      - docker tag lukondefmwila/dkr-multicontainer-app-backend $REPOSITORY_URI:$IMAGE_TAG:backend
      - docker build -t lukondefmwila/dkr-multicontainer-app-nginx ./nginx
      - docker tag lukondefmwila/dkr-multicontainer-app-nginx $REPOSITORY_URI:$IMAGE_TAG:nginx

  post_build:
    commands:
      # Take these images and push them to Docker hub
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push lukondefmwila/dkr-multicontainer-app-client
      - docker push lukondefmwila/dkr-multicontainer-app-backend
      - docker push lukondefmwila/dkr-multicontainer-app-nginx
        
      # - echo Pushing the Docker images...
      # - docker push $REPOSITORY_URI:latest
      # - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"hello-world","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json